minibus_order/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('about-us/', views.AboutUsView.as_view(), name='about_us'),
    path('order/', include('orders.urls', namespace='order')),
    path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('search/', views.SearchRoutesView.as_view(), name='search'),
    path('routes/', views.RoutesView.as_view(), name='routes'),
    path('create-order/<int:route_id>', views.CreateOrderView.as_view(), name='create_order'),
    path('cancel-order/<int:pk>', views.CancelOrderView.as_view(), name='cancel_order'),
    path('orders/', views.OrdersView.as_view(), name='orders'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('sign-in/', views.SignInView.as_view(), name='sign_in'),
    path('sign-up/', views.SignUpView.as_view(), name='sign_up'),
    path('sign-out/', LogoutView.as_view(), name='sign_out'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile')
]

orders/models.py
from datetime import date

from django.db import models
from django.utils.translation import gettext_lazy as _

from base.models import Base
from users import models as users_models


class Route(Base):
    class FromWhereToWhere(models.TextChoices):
        route_1 = 'RE1', _('For example A')
        route_2 = 'RE2', _('For example B')

    route = models.CharField(max_length=3, choices=FromWhereToWhere.choices, default=FromWhereToWhere.route_1)
    departure_datetime = models.DateTimeField()
    driver = models.ForeignKey(to=users_models.Employee, on_delete=models.SET_NULL, blank=True, null=True)
    number_of_seats = models.PositiveIntegerField(default=15)

    class Meta:
        verbose_name = _('Route')
        verbose_name_plural = _('Routes')

    def __str__(self):
        return f'{self.driver} | {self.departure_datetime:%d-%m-%Y %H:%M}'

    def is_overdue_route(self):
        return self.departure_datetime.date() < date.today()


class Order(Base):
    class LandingSites(models.TextChoices):
        place_1 = 'FE1', _('For example 1')
        place_2 = 'FE2', _('For example 2')
        place_3 = 'FE3', _('For example 3')

    user = models.ForeignKey(to=users_models.User, on_delete=models.CASCADE)
    route = models.ForeignKey(to=Route, on_delete=models.CASCADE)
    landing_site = models.CharField(max_length=3, choices=LandingSites.choices)

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return f'{_("Route")}: {self.route.departure_datetime:%d-%m-%Y %H:%M} |' \
               f' {_("User")}: {self.user.first_name} {self.user.last_name}'

orders/forms.py
from django import forms

from orders.models import Order, Route


class SearchRoutesForms(forms.ModelForm):
    class DateInput(forms.DateInput):
        input_type = 'date'

    route = forms.CharField(widget=forms.Select(
        choices=Route.FromWhereToWhere.choices
    ))

    departure_datetime = forms.DateField(widget=DateInput())

    class Meta:
        model = Route
        fields = ('route', 'departure_datetime')


class CreateOrderForm(forms.ModelForm):
    landing_site = forms.CharField(widget=forms.Select(
        choices=Order.LandingSites.choices
    ))

    class Meta:
        model = Order
        fields = ('landing_site',)

orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (CreateView, DeleteView, FormView, ListView,
                                  TemplateView)

from common.mixins import TitleMixin
from orders.forms import CreateOrderForm, SearchRoutesForms
from orders.mixins import CheckCancelOrderMixin, CheckCreateOrderMixin
from orders.models import Order, Route
from orders.services import (add_parameters_form, check_departure_date,
                             increase_number_of_seats, reduce_number_of_seats)


class IndexView(
    TitleMixin,
    TemplateView
):
    template_name = 'orders/index.html'
    title = _('Main')


class AboutUsView(
    TitleMixin,
    TemplateView
):
    template_name = 'orders/about.html'
    title = _('About us')


class SearchRoutesView(
    TitleMixin,
    LoginRequiredMixin,
    FormView
):
    template_name = 'orders/search_routes.html'
    title = _('Search route')
    form_class = SearchRoutesForms


class RoutesView(
    TitleMixin,
    LoginRequiredMixin,
    ListView
):
    template_name = 'orders/routes.html'
    title = _('Routes')
    model = Route

    def get_queryset(self):
        departure_date = self.request.GET.get('departure_datetime')

        if check_departure_date(departure_date):
            return Route.objects.filter(
                route=self.request.GET.get('route'),
                departure_datetime__date=departure_date
            )

        return ()


class CreateOrderView(
    TitleMixin,
    CheckCreateOrderMixin,
    CreateView
):
    template_name = 'orders/create_order.html'
    title = _('Confirmation')
    model = Order
    form_class = CreateOrderForm

    def form_valid(self, form):
        instance = form.save(commit=False)
        add_parameters_form(self, instance)
        reduce_number_of_seats(self.kwargs.get('route_id'))

        return HttpResponseRedirect('/order/orders')


class CancelOrderView(
    CheckCancelOrderMixin,
    DeleteView
):
    model = Order
    success_url = reverse_lazy('order:orders')

    def get(self, request, *args, **kwargs):
        increase_number_of_seats(kwargs.get('pk'))
        return self.post(request, *args, **kwargs)


class OrdersView(
    TitleMixin,
    LoginRequiredMixin,
    ListView
):
    template_name = 'users/orders.html'
    title = _('Orders')
    model = Order

    def get_queryset(self):
        return sorted(
            Order.objects.filter(user_id=self.request.user.id),
            key=lambda obj: obj.route.departure_datetime,
            reverse=True
        )

orders/templates/orders/about.html
{% extends 'base/base.html' %}
{% load static %}

{% block main %}
<section class="about_section layout_padding2-bottom">
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="heading_style">О нас</h2>
            </div>

        </div>
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'images/a-truck.jpg' %}" alt="" class="img-fluid">
            </div>
            <div class="col-md-6 about_detail-container">
                <div class="about_detail-box">
                    <h3>Пассажирские перевозки</h3>
                    <p>
                        Наша команда состоит из опытных водителей и профессиональных диспетчеров, которые всегда готовы
                        помочь вам выбрать наиболее удобное время и место для поездки. Мы предлагаем широкий выбор
                        автомобилей различных классов, чтобы удовлетворить потребности каждого клиента. Наша цель —
                        обеспечить безопасность и комфорт во время вашей поездки.
                    </p>
                    <div class="d-flex  justify-content-end">
                        <a href="{% url 'index' %}" class="quote-btn about-btn">
                            <img src="{% static 'images/white-next.png' %}" alt="">
                            <span>На главную</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/create_order.html
{% extends 'base/base.html' %}

{% block main %}
<div class="col-lg-7" style="margin-left:auto; margin-right:auto;">
    <h4 class="mt-3 mb-3" style="text-align: center;">Оформление</h4>
    <form method="POST" style="margin: 10px 20px 30px 40px;">
        {% csrf_token %}

        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="inputFirstName">Имя</label>
                    <input class="form-control py-4" id="inputFirstName" type="text"
                           value="{{ request.user.first_name }}" disabled/>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="inputLastName">Фамилия</label>
                    <input class="form-control py-4" id="inputLastName" type="text"
                           value="{{ request.user.last_name }}" disabled/>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="inputUsername">Маршрут</label>
                <input class="form-control py-4" id="inputRoure" type="text"
                       aria-describedby="usernameHelp"
                       value="{{ user.username }}" disabled/>
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="inputEmailAddress">Время отправления</label>
                <input class="form-control py-4" id="inputDepartureDatetime" type="text"
                       aria-describedby="emailHelp"
                       value="{{ user.email }}" disabled/>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-2">
                <label class="small mb-1" for="{{ form.landing_site.id_for_label }}">Место посадки</label>
                {{ form.landing_site }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Подтвердить"
                       style="background-color: skyblue; border-color: skyblue;">
            </div>

        </div>
    </form>
</div>
{% endblock %}

orders/templates/orders/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block main %}
<section class=" slider_section ">
    <div style="background-image: url({% static 'images/main-bg.jpg' %});  background-position:center center;  background-size:cover">
        <div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="container">
                        <div class="slider_item-container">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="slider_item-detail">
                                        <div>
                                            <h1>Заказать транспорт <br>прямо сейчас</h1>
                                            <div class="d-flex">
                                                <div>
                                                    <a href="{% url 'order:search' %}" class="read-btn">
                                                        <span>Заказать</span>
                                                        <img src="{% static 'images/white-next.png' %}" alt="">
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="slider_img-box">
                                        <img src="{% static 'images/truck.png' %}" alt="" class="img-fluid">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</div>


<section class="about_section ">
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="heading_style">Чем мы занимаеся?</h2>

            </div>

        </div>
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'images/map.jpg' %}" alt="" class="img-fluid">
            </div>
            <div class="col-md-6 about_detail-container">
                <div class="about_detail-box">
                    <h3>Пассажирские перевозки</h3>
                    <p>
                        Компания "For example" предоставляет услуги по перевозке пассажиров из города A в город B. Мы
                        гарантируем комфорт и безопасность наших клиентов, используя только самые современные
                        автомобили. Наша команда профессиональных водителей всегда готова к любым ситуациям на дороге и
                        обеспечивает быструю доставку пассажиров в пункт назначения. Вы можете быть уверены, что мы
                        сделаем все возможное для того, чтобы ваш опыт путешествия был максимально приятным и удобным.
                    </p>
                </div>
            </div>
        </div>
    </div>

</section>
{% endblock %}

orders/templates/orders/routes.html
{% extends 'base/base.html' %}

{% block main %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Онлайн бронирование</h1>
            <div class="orders mt-5">
                {% if object_list %}
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">Маршрут</th>
                        <th scope="col">Время отправления</th>
                        <th scope="col">Свободных мест</th>
                        <th scope="col">Место посадки</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for route in object_list %}
                    <tr class="table-exp">
                        <th scope="row">{{ route.get_route_display }}</th>
                        <td>{{ route.departure_datetime }}</td>
                        <td>{{ route.number_of_seats }}</td>
                        <td>
                            <select class="select-css">
                                <option selected="selected">Место 1</option>
                                <option>Место 2</option>
                            </select>
                        </td>
                        <td>
                            <a href="#">Заказать</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p>Не найдено автомобилей на выбранную дату</p>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

orders/templates/orders/search_routes.html
{% extends 'base/base.html' %}

{% block main %}
<section class="layout_padding2-bottom">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Поиск маршрутки</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'order:routes' %}" method="GET">
                            <div class="form-group">
                                <label class="small mb-1">Выберите маршрут</label>
                                {{ form.route }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="inputPassword">Выберите дату</label>
                                {{ form.departure_datetime }}
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a></a>
                                <input class="btn btn-primary" style="background-color: darkblue;border-color: darkblue"
                                       type="submit" value="Поиск">
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}