minibus_order/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('about-us/', views.AboutUsView.as_view(), name='about_us'),
    path('order/', include('orders.urls', namespace='order')),
    path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('search/', views.SearchRoutesView.as_view(), name='search'),
    path('routes/', views.RoutesView.as_view(), name='routes'),
    path('create-order/<int:route_id>', views.CreateOrderView.as_view(), name='create_order'),
    path('cancel-order/<int:pk>', views.CancelOrderView.as_view(), name='cancel_order'),
    path('orders/', views.OrdersView.as_view(), name='orders'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('sign-in/', views.SignInView.as_view(), name='sign_in'),
    path('sign-up/', views.SignUpView.as_view(), name='sign_up'),
    path('sign-out/', LogoutView.as_view(), name='sign_out'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile')
]

orders/models.py
from datetime import date

from django.db import models
from django.utils.translation import gettext_lazy as _

from base.models import Base
from users import models as users_models


class Route(Base):
    class FromWhereToWhere(models.TextChoices):
        route_1 = 'RE1', _('For example A')
        route_2 = 'RE2', _('For example B')

    route = models.CharField(max_length=3, choices=FromWhereToWhere.choices, default=FromWhereToWhere.route_1)
    departure_datetime = models.DateTimeField()
    driver = models.ForeignKey(to=users_models.Employee, on_delete=models.SET_NULL, blank=True, null=True)
    number_of_seats = models.PositiveIntegerField(default=15)

    class Meta:
        verbose_name = _('Route')
        verbose_name_plural = _('Routes')

    def __str__(self):
        return f'{self.driver} | {self.departure_datetime:%d-%m-%Y %H:%M}'

    def is_overdue_route(self):
        return self.departure_datetime.date() < date.today()


class Order(Base):
    class LandingSites(models.TextChoices):
        place_1 = 'FE1', _('For example 1')
        place_2 = 'FE2', _('For example 2')
        place_3 = 'FE3', _('For example 3')

    user = models.ForeignKey(to=users_models.User, on_delete=models.CASCADE)
    route = models.ForeignKey(to=Route, on_delete=models.CASCADE)
    landing_site = models.CharField(max_length=3, choices=LandingSites.choices)

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return f'{_("Route")}: {self.route.departure_datetime:%d-%m-%Y %H:%M} |' \
               f' {_("User")}: {self.user.first_name} {self.user.last_name}'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from base.models import Base
from common.validators import phone_number_validator


class Employee(Base):
    class EmployeePosition(models.TextChoices):
        operator = 'OP', _('Operator')
        driver = 'DR', _('Driver')

    full_name = models.CharField(max_length=128)
    phone_number = models.CharField(validators=[phone_number_validator], max_length=13)
    job_title = models.CharField(max_length=2, choices=EmployeePosition.choices)

    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')

    def __str__(self):
        return f'{self.full_name} | {self.phone_number} | {self.job_title}'


class User(AbstractUser, Base):
    first_name = models.CharField(_('first name'), max_length=32)
    last_name = models.CharField(_('last name'), max_length=32)
    image = models.ImageField(upload_to='user_images', blank=True, null=True)
    phone_number = models.CharField(validators=[phone_number_validator], max_length=13)

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def __str__(self):
        return f'{self.first_name} {self.last_name} | {self.phone_number}'

orders/forms.py
from django import forms

from orders.models import Order, Route


class SearchRoutesForms(forms.ModelForm):
    class DateInput(forms.DateInput):
        input_type = 'date'

    route = forms.CharField(widget=forms.Select(
        choices=Route.FromWhereToWhere.choices
    ))

    departure_datetime = forms.DateField(widget=DateInput())

    class Meta:
        model = Route
        fields = ('route', 'departure_datetime')


class CreateOrderForm(forms.ModelForm):
    landing_site = forms.CharField(widget=forms.Select(
        choices=Order.LandingSites.choices
    ))

    class Meta:
        model = Order
        fields = ('landing_site',)

users/forms.py
from django import forms
from django.contrib.auth import forms as f
from django.utils.translation import gettext_lazy as _

from common.validators import phone_number_validator
from users.models import User


class SignInForm(f.AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': _('Enter your username')
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': _('Enter password')
    }))

    class Meta:
        model = User
        fields = ('username', 'password')


class SignUpForm(f.UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'id': 'inputFirstName',
        'placeholder': _('Enter your name')
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'id': 'inputLastName',
        'placeholder': _('Enter last name')
    }))

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'id': 'inputUsername',
        'placeholder': _('Enter your username')
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'id': 'inputEmailAddress',
        'placeholder': _('Enter your email address')
    }))

    phone_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'id': 'inputPhoneNumber',
        'placeholder': _('Enter your phone number')
    }), validators=(phone_number_validator,))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'id': 'inputPassword',
        'placeholder': _('Enter password')
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'id': 'inputConfirmPassword',
        'placeholder': _('Confirm the password')
    }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'phone_number', 'password1', 'password2')


class ProfileUpdateForm(f.UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'id': 'inputFirstName'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'id': 'inputLastName'
    }))

    phone_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'id': 'inputPhoneNumber'
    }))

    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'custom-file-label',
        'id': 'userAvatar',
        'size': '50'
    }), required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'phone_number', 'image')

orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (CreateView, DeleteView, FormView, ListView,
                                  TemplateView)

from common.mixins import TitleMixin
from orders.forms import CreateOrderForm, SearchRoutesForms
from orders.mixins import CheckCancelOrderMixin, CheckCreateOrderMixin
from orders.models import Order, Route
from orders.services import (add_parameters_form, check_departure_date,
                             increase_number_of_seats, reduce_number_of_seats)


class IndexView(
    TitleMixin,
    TemplateView
):
    template_name = 'orders/index.html'
    title = _('Main')


class AboutUsView(
    TitleMixin,
    TemplateView
):
    template_name = 'orders/about.html'
    title = _('About us')


class SearchRoutesView(
    TitleMixin,
    LoginRequiredMixin,
    FormView
):
    template_name = 'orders/search_routes.html'
    title = _('Search route')
    form_class = SearchRoutesForms


class RoutesView(
    TitleMixin,
    LoginRequiredMixin,
    ListView
):
    template_name = 'orders/routes.html'
    title = _('Routes')
    model = Route

    def get_queryset(self):
        departure_date = self.request.GET.get('departure_datetime')

        if check_departure_date(departure_date):
            return Route.objects.filter(
                route=self.request.GET.get('route'),
                departure_datetime__date=departure_date
            )

        return ()


class CreateOrderView(
    TitleMixin,
    CheckCreateOrderMixin,
    CreateView
):
    template_name = 'orders/create_order.html'
    title = _('Confirmation')
    model = Order
    form_class = CreateOrderForm

    def form_valid(self, form):
        instance = form.save(commit=False)
        add_parameters_form(self, instance)
        reduce_number_of_seats(self.kwargs.get('route_id'))

        return HttpResponseRedirect('/order/orders')


class CancelOrderView(
    CheckCancelOrderMixin,
    DeleteView
):
    model = Order
    success_url = reverse_lazy('order:orders')

    def get(self, request, *args, **kwargs):
        increase_number_of_seats(kwargs.get('pk'))
        return self.post(request, *args, **kwargs)


class OrdersView(
    TitleMixin,
    LoginRequiredMixin,
    ListView
):
    template_name = 'users/orders.html'
    title = _('Orders')
    model = Order

    def get_queryset(self):
        return sorted(
            Order.objects.filter(user_id=self.request.user.id),
            key=lambda obj: obj.route.departure_datetime,
            reverse=True
        )

users/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, UpdateView

from common.mixins import TitleMixin
from users.forms import ProfileUpdateForm, SignInForm, SignUpForm
from users.mixins import LogoutRequiredMixin, UserCheckMixin
from users.models import User


class SignInView(
    TitleMixin,
    LogoutRequiredMixin,
    LoginView
):
    template_name = 'users/sign_in.html'
    title = _('Sign in')
    form_class = SignInForm

    def get_redirect_url(self):
        return reverse_lazy('user:profile', kwargs={'pk': self.request.user.id})


class SignUpView(
    TitleMixin,
    LogoutRequiredMixin,
    CreateView
):
    template_name = 'users/sign_up.html'
    title = _("Sign up")
    model = User
    form_class = SignUpForm
    success_url = reverse_lazy('user:sign_in')


class ProfileView(
    TitleMixin,
    UserCheckMixin,
    UpdateView
):
    template_name = 'users/profile.html'
    title = _('Profile')
    model = User
    form_class = ProfileUpdateForm

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

users/templates/users/orders.html
{% extends 'base/base.html' %}

{% block main %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Мои заказы</h1>
            <div class="orders mt-5">
                {% if object_list %}
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">Маршрут</th>
                        <th scope="col">Время отправления</th>
                        <th scope="col">Место посадки</th>
                        <th scope="col">Действие</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for order in object_list %}
                    <tr class="table-exp">
                        <th scope="row">{{ order.route.get_route_display }}</th>
                        <td>{{ order.route.departure_datetime }}</td>
                        <td>{{ order.landing_site }}</td>
                        <td>
                            {% if order.route.is_overdue_route %}
                            <p>Отменить</p>
                            {% else %}
                            <a href="{% url 'order:cancel_order' order.id %}">Отменить</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p>У вас нет заказов</p>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/users/profile.html
{% extends 'base/base.html' %}
{% load static %}

{% block main %}
<div class="col-lg-7" style="margin-left:auto; margin-right:auto;">
    <h4 class="mt-3 mb-3" style="text-align: center;">Профиль</h4>
    <div class="col-lg-12 text-center">
        <img width="100" height="100"
             {% if user.image %}
             src="{{ user.image.url }}"
             {% else %}
             src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22200%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20200%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1765bc6c014%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A10pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1765bc6c014%22%3E%3Crect%20width%3D%22200%22%20height%3D%22200%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2274.421875%22%20y%3D%22104.65%22%3E200x200%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
             {% endif %}
             class="img-thumbnail">
    </div>
    <form method="post" style="margin: 10px 20px 30px 40px;" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.phone_number.id_for_label }}">Номер телефона</label>
                    {{ form.phone_number }}
                    {% if form.errors %}
                    <h6 style="color: red">Номер телефона должен быть введен в формате:<br>
                        1. +375XXXXXXXXX<br>
                        2. 80XXXXXXXXX
                    </h6>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="form-row mb-2">
            <div class="col-lg-12">
                <div class="custom-file">
                    {{ form.image }}
                    <label class="custom-file-label" for="userAvatar">Выберите изображение</label>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="inputUsername">Имя пользователя</label>
                <input class="form-control py-4" id="inputUsername" type="text"
                       aria-describedby="usernameHelp"
                       value="{{ user.username }}" disabled/>
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="inputEmailAddress">Адрес электронной
                    почты</label>
                <input class="form-control py-4" id="inputEmailAddress" type="email"
                       aria-describedby="emailHelp"
                       value="{{ user.email }}" disabled/>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                <a href="{% url 'order:orders' %}" class="btn btn-info btn-block">
                    Мои заказы
                </a>
                <a href="{% url 'user:sign_out' %}" class="btn btn-info btn-block">
                    Выйти
                </a>
            </div>

        </div>
    </form>
</div>
{% endblock %}

users/templates/users/sign_in.html
{% extends 'base/base.html' %}
{% load static %}

{% block main %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert"
                     style="margin-top: 50px; background-color: skyblue; color: white; border-color: wheat;">
                    <h6 align="center">Неверный логин или пароль!</h6>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'user:sign_in' %}" method="post">
                            {% csrf_token %}

                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                                    пользователя</label>
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                {{ form.password }}
                            </div>
                            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                <a class="small" href="#" style="color: black;">Забыли пароль?</a>
                                <input class="btn btn-primary"
                                       style="background-color: darkblue;border-color: darkblue;" type="submit"
                                       value="Авторизоваться">
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'user:sign_up' %}" style="color: black;">Нужен аккаунт?
                            Зарегистрируйся!</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/sign_up.html
{% extends 'base/base.html' %}
{% load static %}

{% block main %}
<main>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert"
                     style="margin-top: 50px;background-color: skyblue; color: white; border-color: wheat;">
                    <h5 align="center">Исправьте следующие ошибки</h5><br>
                    <ul>
                        {% for _, errors in form.errors.items %}
                        {% for error in errors %}
                        <li><h6>{{ error }}</h6></li>
                        {% endfor %}
                        {% endfor %}
                    </ul>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                <div class="card shadow-lg border-0 rounded-lg mt-5">
                    <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                    </div>
                    <div class="card-body">
                        <form action="{% url 'user:sign_up' %}" method="post">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                        {{ form.first_name }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1"
                                               for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-6">
                                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                                        пользователя</label>
                                    {{ form.username }}
                                </div>
                                <div class="col-md-6">
                                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                        почты</label>
                                    {{ form.email }}
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="col-md-12">
                                    <label class="small mb-1" for="{{ form.phone_number.id_for_label }}">Номер телефона
                                    </label>
                                    {{ form.phone_number }}
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                        {{ form.password1 }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                            пароля</label>
                                        {{ form.password2 }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mt-4 mb-0">
                                <input class="btn btn-primary btn-block"
                                       style="background-color: darkblue;border-color: darkblue;" type="submit"
                                       value="Создать аккаунт">
                            </div>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <div class="small"><a href="{% url 'user:sign_in' %}" style="color: black;">Уже есть аккаунт?
                            Авторизоваться</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}