minibus_order/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from orders import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('about-us/', views.AboutUsView.as_view(), name='about_us'),
    path('order/', include('orders.urls', namespace='order')),
    path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('sign-in/', views.SignInView.as_view(), name='sign_in'),
    path('sign-up/', views.SignUpView.as_view(), name='sign_up'),
    path('sign-out/', LogoutView.as_view(), name='sign_out'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile')
]

base/models.py
from django.db import models


class Base(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Basic -->
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <!-- Site Metas -->
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>

    <title>{{ title }}</title>

    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css"/>

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <!-- responsive style -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet"/>
</head>

<body>
<div class="hero_area custom_page-height">
    <!-- header section strats -->
    <section class="header_section">
        <div class="container">
            <nav class="navbar navbar-expand-lg custom_nav-container d-lg-none">
                <a class="navbar-brand" href="#">
                    <div class="logo-box">
                        <img src="{% static 'images/logo.png' %}" alt="">
                        <span>For example</span>
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav  ">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'index' %}">Главная <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'about_us' %}">О нас</a>
                        </li>
                        <li class="nav-item ">
                            {% if user.is_authenticated %}
                                <a class="nav-link " href="{% url 'user:profile' user.id %}">Профиль</a>
                            {% else %}
                                <a class="nav-link " href="{% url 'user:sign_up' %}">Вход</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="header_container ">
                <div class="logo-box">
                    <img src="{% static 'images/logo.png' %}" alt="">
                    <span>For example</span>
                </div>
                <div>
                    <div class="header_top">
                        <div class="header_top-contact">

                            <a href="" class="ml-4">
                                <div>
                                    <img src="{% static 'images/phone.png '%}" alt=""/>
                                </div>
                                <span>+375xxxxxxxxx</span>
                            </a>
                            <a href="" class="ml-4">
                                <div>
                                    <img src="{% static 'images/mail.png' %}" alt=""/>
                                </div>
                                <span>forexample@gmail.com</span>
                                <br>
                                <br>
                            </a>
                        </div>

                    </div>
                    <div class="header_btm">
                        <nav class="navbar navbar-expand-lg custom_nav-container pt-0">

                            <button class="navbar-toggler" type="button" data-toggle="collapse"
                                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                    aria-expanded="false"
                                    aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>

                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
                                    <ul class="navbar-nav  ">
                                        <li class="nav-item active">
                                            <a class="nav-link" href="{% url 'index' %}">Главная <span class="sr-only">(current)</span></a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'about_us' %}">О нас</a>
                                        </li>
                                        <li class="nav-item ">
                                            {% if user.is_authenticated %}
                                                <a class="nav-link pr-0" href="{% url 'user:profile' user.id %}">Профиль</a>
                                            {% else %}
                                                <a class="nav-link pr-0" href="{% url 'user:sign_in' %}">Вход</a>
                                            {% endif %}
                                        </li>
                                    </ul>

                                </div>

                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end header section -->
</div>

<!-- main section -->
{% block main %} {% endblock %}
<!-- end main section -->


<!-- info section -->
<section class="info_section ">
    <div class="container ">
        <div class="row  mb-3 pb-4">
            <div class="col-md-3 info_logo">
                <div class="logo-box">
                    <img src="{% static 'images/logo-white.png' %}" alt="">
                    <span>For example</span>
                </div>
            </div>
            <div class="col-md-3 info_news">
                <h5>
                    Наши контакты
                </h5>
                <p>+375xxxxxxxxx</p>
                <p>+375xxxxxxxxx</p>
                <p><a href="">forexample@gmail.com</a></p>
            </div>
            <div class="col-md-3 info_links">

                <div class="info_nav ">
                    <nav class="">
                        <ul>
                            <h5>Ссылки</h5>
                            <li>
                                <a href="{% url 'index' %}">Главная</a>
                            </li>
                            <li>
                                <a href="{% url 'about_us' %}">О нас</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
             <div class="col-md-3 info_address">
                <h5>Наш адрес</h5>
                <p>For example</p>
            </div>
        </div>
    </div>
</section>
<!-- end info section -->

<!-- footer section -->
<section class="container-fluid footer_section">
    <p>Copyright &copy; 2019 All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
    </p>
</section>
<!-- footer section -->

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

</body>
</html>